name: Build UCRT64
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            autoconf
            automake
            libtool
            base-devel
            glib2-devel

      - name: Install gcc
        run: |
          pacman -U ./gcc/mingw-w64-ucrt-x86_64-gcc-11.3.0-1-any.pkg.tar.zst ./gcc/mingw-w64-ucrt-x86_64-gcc-libs-11.3.0-1-any.pkg.tar.zst ./gcc/mingw-w64-ucrt-x86_64-crt-git-10.0.0.r14.ga08c638f8-1-any.pkg.tar.zst --noconfirm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/mdbtools/mdbtools.git

      - name: Debug
        run: |
          gcc -v
          ls
          pwd
