name: Build UCRT64
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Mdbtools
        run: |
          git clone --depth=1 https://github.com/mdbtools/mdbtools.git

      - name: Patch
        run: |
          cd mdbtools
          git apply ../patch_file.patch
          git apply ../patch_configure.patch

      - name: Setup MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            autoconf
            automake
            libtool
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-glib2

      - name: Debug
        shell: msys2 {0}
        run: |
          gcc -v
          ls
          pwd

      - name: Autoconf
        shell: msys2 {0}
        # 当前目录/d/a/mdbtools-win-build-action/mdbtools-win-build-action  又回到上一级目录了
        run: cd mdbtools && autoreconf -i -f

      - name: Configure
        shell: msys2 {0}
        run: cd mdbtools && ./configure

      - name: Make
        shell: msys2 {0}
        run: cd mdbtools && make all

      - name: Test
        shell: msys2 {0}
        run: |
          cd mdbtools
          ./src/util/mdb-export.exe --version
          ldd ./src/util/mdb-export.exe
