name: Build MINGW32 (tweak)
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW32
    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/mdbtools/mdbtools.git
      - name: Setup MINGW64 Build Environment (using gcc 11.3.0)
        run: |
          C:\msys64\usr\bin\bash -c -l 'pacman -Syu'
          C:\msys64\usr\bin\bash -c -l 'wget https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-gcc-11.3.0-1-any.pkg.tar.zst'
          C:\msys64\usr\bin\bash -c -l 'wget https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-gcc-libs-11.3.0-1-any.pkg.tar.zst'
          C:\msys64\usr\bin\bash -c -l 'wget https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-crt-git-10.0.0.r14.ga08c638f8-1-any.pkg.tar.zst'
          C:\msys64\usr\bin\bash -c -l 'pacman -U mingw-w64-i686-gcc-11.3.0-1-any.pkg.tar.zst mingw-w64-i686-gcc-libs-11.3.0-1-any.pkg.tar.zst mingw-w64-i686-crt-git-10.0.0.r14.ga08c638f8-1-any.pkg.tar.zst --noconfirm'
          C:\msys64\usr\bin\bash -c -l 'pacman -S --needed base-devel --noconfirm'
          C:\msys64\usr\bin\bash -c -l 'pacman -S autoconf automake libtool --noconfirm'
      - name: Replace Horizontal Ellipsis
        run: |
          C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE/mdbtools" && sed -i "s#\\\\\\\\xE2\\\\\\\\x80\\\\\\\\xA6#...#" ./src/libmdb/fakeglib.c'
      - name: Autoconf
        run: |
          C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE/mdbtools" && autoreconf -i -f'
      - name: Configure
        run: |
          C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE/mdbtools" && ./configure'
      - name: Make
        run: |
          C:\msys64\usr\bin\bash -c -l 'cd "$GITHUB_WORKSPACE/mdbtools" && make all'
      - name: Orgnize file
        run: |
          mkdir mdbtools-build-win-MINGW32-tweak
          cp ./mdbtools/COPYING* ./mdbtools-build-win-MINGW32-tweak/
          cp ./mdbtools/src/util/.libs/*.exe ./mdbtools-build-win-MINGW32-tweak/
          cp ./mdbtools/src/sql/.libs/*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp ./mdbtools/src/libmdb/.libs/*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp C:/msys64/mingw32/bin/libgcc*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp C:/msys64/mingw32/bin/libiconv*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp C:/msys64/mingw32/bin/libreadline*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp C:/msys64/mingw32/bin/libtermcap*.dll ./mdbtools-build-win-MINGW32-tweak/
          cp C:/msys64/mingw32/bin/libwinpthread*.dll ./mdbtools-build-win-MINGW32-tweak/
          ls ./mdbtools-build-win-MINGW32-tweak/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'mdbtools-build-win-MINGW32-tweak'
          path: ./mdbtools-build-win-MINGW32-tweak/
