name: Build UCRT64
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup UCRT64 Build Environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            autotools
            base-devel
            gcc
            git
            glib2-devel

      - name: Clone repository
        run: |
          git clone https://github.com/mdbtools/mdbtools.git

      - name: Autoconf
        run: cd mdbtools && autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make all
      - name: Orgnize file
        run: |
          mkdir mdbtools-build-win-UCRT64
          cp ./mdbtools/COPYING* ./mdbtools-build-win-UCRT64/
          cp ./mdbtools/src/util/.libs/*.exe ./mdbtools-build-win-UCRT64/
          cp ./mdbtools/src/sql/.libs/*.dll ./mdbtools-build-win-UCRT64/
          cp ./mdbtools/src/libmdb/.libs/*.dll ./mdbtools-build-win-UCRT64/
          cp C:/msys64/ucrt64/bin/libgcc*.dll ./mdbtools-build-win-UCRT64/
          cp C:/msys64/ucrt64/bin/libiconv*.dll ./mdbtools-build-win-UCRT64/
          cp C:/msys64/ucrt64/bin/libreadline*.dll ./mdbtools-build-win-UCRT64/
          cp C:/msys64/ucrt64/bin/libtermcap*.dll ./mdbtools-build-win-UCRT64/
          cp C:/msys64/ucrt64/bin/libwinpthread*.dll ./mdbtools-build-win-UCRT64/
          ls ./mdbtools-build-win-UCRT64/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'mdbtools-build-win-UCRT64'
          path: ./mdbtools-build-win-UCRT64/
