name: Build UCRT64
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Mdbtools
        run: |
          git clone --depth=1 https://github.com/mdbtools/mdbtools.git

      - name: Patch
        run: |
          cd mdbtools
          git apply ../patch_file.patch
