name: Build UCRT64
on:
  workflow_dispatch:

jobs:
  build-mdbtools-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Mdbtools
        run: |
          git clone --depth=1 https://github.com/mdbtools/mdbtools.git

      - name: Patch
        run: |
          cd mdbtools
          git apply ../patch_file.patch
