name: MSYS2
on: workflow_dispatch

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: base-devel autoconf automake libtool
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          uname -a
          wget https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-11.3.0-1-any.pkg.tar.zst
          wget https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-libs-11.3.0-1-any.pkg.tar.zst
          wget https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-crt-git-10.0.0.r14.ga08c638f8-1-any.pkg.tar.zst
          pacman -U mingw-w64-ucrt-x86_64-gcc-libs-11.3.0-1-any.pkg.tar.zst  mingw-w64-ucrt-x86_64-gcc-11.3.0-1-any.pkg.tar.zst  mingw-w64-ucrt-x86_64-crt-git-10.0.0.r14.ga08c638f8-1-any.pkg.tar.zst --noconfirm
          pacman -S git pkg-config m4 --noconfirm
          git clone https://github.com/mdbtools/mdbtools.git
          cd mdbtools
          autoreconf -i -f
          ./configure 
          make all
