name: MSYS2
on: workflow_dispatch

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git base-devel mingw-w64-x86_64-toolchain autoconf automake libtool
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          uname -a
          git clone https://github.com/mdbtools/mdbtools.git
          cd mdbtools
          autoreconf -i -f
          ./configure 
          make all
